### ISSUE TITLE
Start/stop not functioning

### ISSUE THREAD

**Issue by Werdana74** [Uranium2/Auto_Hekili#2]
hi, first of all thanks for your effort.
F3 button only works on the interface we choose specs and windows not working in WoW game client window. So when start and change window since it starts to push buttons sometimes writes on programe or some of the window boxes. And when it starts you cant stop or pause it by F3, you need to shut it by closing window ot ctrl+alt+del.
Can you help what to do to make it work to work by a key press while on Wow client window and able to pause it ingame?

**Comment by Uranium2** [comment]
Hello;
Thanks for the feed back, it's been a while I didn't touch this code. But from my README, F3 should be working even if the python client is not selected.

`Press F3 to toggle on or off the prediction. Make sure to select World of Warcraft game client. Else it will send keys to wherever you pressed.`

I even say to select WoW client else it will send keys all over the place. Maybe try to have WoW client in windowed mode ? I don't play WoW anymore, but I remember that I never played it in Fullscreen since I like to use my second monitor
